name: pearl_server_dartfrog
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  get_it: ^7.6.7
  http: ^1.2.0
  rpi_gpio: ^0.9.1
  shelf_cors_headers: ^0.1.5
  

dev_dependencies:
  mockito: ^5.0.0
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
  